=head1 NAME

Hub::Base::NoOp - 

Part of the L<Hub Library|hublib>

=head1 SYNOPSIS



=head1 DESCRIPTION



=head1 METHODS

=begin html

<table><tr><td>
<a class="methlink" href="#item_new">new</a>

</td></tr></table>

=end html


=over 4

=item new

B<>



=back

=head1 INTERNAL

=begin html

<table><tr><td>
<a class="methlink" href="#item_autoload">AUTOLOAD</a>

</td><td>
<a class="methlink" href="#item_destroy">DESTROY</a>

</td></tr></table>

=end html


=over 4

=item AUTOLOAD

B<>



=back

=over 4

=item DESTROY

B<>



=back

=head1 AUTHOR



Ryan Gies

=head1 COPYRIGHT



Copyright (c) 2006 Livesite Networks, LLC.  All rights reserved.

Copyright (c) 2000-2005 Ryan Gies.  All rights reserved.

=head1 UPDATED

This file created by  on  at 

=cut
