=head1 NAME

Hub::Base::Package - 

Part of the L<Hub Library|hublib>

=head1 SYNOPSIS



=head1 DESCRIPTION



=head1 METHODS

=begin html

<table><tr><td>
<a class="methlink" href="#item_call">call</a>

</td><td>
<a class="methlink" href="#item_modexec">modexec</a>

</td><td>
<a class="methlink" href="#item_new">new</a>

</td><td>
<a class="methlink" href="#item_parsefile">parsefile</a>

</td></tr></table>

=end html


=over 4

=item call

B<>

 Usage: call METHOD, [ARGS]

Call a method in the representing package
Note that AUTOLOAD methods do not pass the 'defined' test


=back

=over 4

=item modexec

B<Execute runtime module>




=back

=over 4

=item new

B<>

 Usage: new FILENAME

Constructor
This is a singleton


=back

=over 4

=item parsefile

B<>

 Usage: parsefile INSTANCE

Called implicty on the first attachment or when the file has been modified
on disk.



=back


=head1 INTERNAL

=begin html

<table><tr><td>
<a class="methlink" href="#item_autoload">AUTOLOAD</a>

</td><td>
<a class="methlink" href="#item_destroy">DESTROY</a>

</td></tr></table>

=end html


=over 4

=item AUTOLOAD

B<>

 Usage: AUTOLOAD

Call a method in the representing package
Note! Use the subroutine 'call' to access methods which are already
implemented in this class (new|call|parsefile).



=back

=over 4

=item DESTROY

B<>

 Usage: DESTROY

Defining this function prevents it from being searched in AUTOLOAD


=back


=head1 AUTHOR


Ryan Gies

=head1 COPYRIGHT


Copyright (c) 2006 Livesite Networks, LLC.  All rights reserved.

Copyright (c) 2000-2005 Ryan Gies.  All rights reserved.

=head1 UPDATED

This file created by mkdocs.pl on 8/29/2006 at 2:07pm

=cut
