=head1 NAME

Hub::Base::Path - 

Part of the L<Hub Library|hublib>

=head1 SYNOPSIS



=head1 DESCRIPTION



=head1 METHODS

=begin html

<table><tr><td>
<a class="methlink" href="#item_new">new</a>

</td><td>
<a class="methlink" href="#item_popwp">popwp</a>

</td><td>
<a class="methlink" href="#item_pushwp">pushwp</a>

</td><td>
<a class="methlink" href="#item_resdir">resdir</a>

</td><td>
<a class="methlink" href="#item_srcpath">srcpath</a>

</td></tr><tr><td>
<a class="methlink" href="#item_popsp">popsp</a>

</td><td>
<a class="methlink" href="#item_pushsp">pushsp</a>

</td><td>
<a class="methlink" href="#item_refresh">refresh</a>

</td><td>
<a class="methlink" href="#item_respath">respath</a>

</td></tr></table>

=end html


=over 4

=item new

B<>

 Usage: new

Constructor


=back

=over 4

=item popsp

B<>

 Usage: popsp

Pop path from source directory stack


=back

=over 4

=item popwp

B<>

 Usage: popwp

Pop path from working directory stack


=back

=over 4

=item pushsp

B<>

 Usage: pushsp

Push path onto source directory stack


=back

=over 4

=item pushwp

B<>

 Usage: pushwp

Push path onto working directory stack


=back

=over 4

=item refresh

B<>

 Usage: refresh

Initialize


=back

=over 4

=item resdir

B<>

 Usage: resdir

Resource directory


=back

=over 4

=item respath

B<>

 Usage: respath

Resource file


=back

=over 4

=item srcpath

B<>

 Usage: srcpath

Source path


=back


=head1 INTERNAL

=begin html



=end html


=head1 AUTHOR


Ryan Gies

=head1 COPYRIGHT


Copyright (c) 2006 Livesite Networks, LLC.  All rights reserved.

Copyright (c) 2000-2005 Ryan Gies.  All rights reserved.

=head1 UPDATED

This file created by mkdocs.pl on 8/29/2006 at 2:07pm

=cut
