=head1 NAME

hublib - Hub Library Reference

=head1 MANUALS

=over 4

=item L<hubaddr|hubaddr>

=item L<hublib|hublib>

=item L<hubparse|hubparse>

=item L<hubtest|hubtest>

=item L<hubuse|hubuse>

=item L<hubvar|hubvar>

=back


=head1 METHODS

=over 4

=item L<abort|Hub::Perl::Language/abort>

=item L<abspath|Hub::Base::FileSystem/abspath>

=item L<anon_sort|Hub::Perl::Sort/anon_sort>

=item L<bestof|Hub::Perl::Language/bestof>

=item L<callback|Hub/callback>

=item L<check|Hub::Perl::Language/check>

=item L<checksum|Hub::Perl::Language/checksum>

=item L<chperm|Hub::Base::FileSystem/chperm>

=item L<cmdopts|Hub::Perl::Language/cmdopts>

=item L<collapse|Hub::Data::Address/collapse>

=item L<compare|Hub::Perl::Compare/compare>

=item L<cpdir|Hub::Base::FileSystem/cpdir>

=item L<cpfile|Hub::Base::FileSystem/cpfile>

=item L<cpref|Hub::Perl::Language/cpref>

=item L<datetime|Hub::Misc::Time/datetime>

=item L<delete|Hub::Data::Handlers/delete>

=item L<dhms|Hub::Misc::Time/dhms>

=item L<dice|Hub::Perl::Language/dice>

=item L<diff|Hub::Perl::Language/diff>

=item L<digout|Hub::Perl::Language/digout>

=item L<dotaddr|Hub::Data::Address/dotaddr>

=item L<expand|Hub::Data::Address/expand>

=item L<expect|Hub::Perl::Language/expect>

=item L<fattach|Hub::Data::FileCache/fattach>

=item L<fcols|Hub::Console::Output/fcols>

=item L<fear|Hub::Perl::Language/fear>

=item L<fetch|Hub::Data::Handlers/fetch>

=item L<fhandler|Hub::Data::FileCache/fhandler>

=item L<fileclose|Hub::Base::FileSystem/fileclose>

=item L<fileopen|Hub::Base::FileSystem/fileopen>

=item L<filetime|Hub::Base::FileSystem/filetime>

=item L<find|Hub::Base::FileSystem/find>

=item L<finstance|Hub::Data::FileCache/finstance>

=item L<fixpath|Hub::Base::FileSystem/fixpath>

=item L<flatten|Hub::Perl::Language/flatten>

=item L<flip|Hub::Perl::Language/flip>

=item L<fread|Hub::Data::FileCache/fread>

=item L<frefresh|Hub::Data::FileCache/frefresh>

=item L<fw|Hub::Console::Output/fw>

=item L<get_save_handler|Hub::Data::Create/get_save_handler>

=item L<getaddr|Hub::Base::FileSystem/getaddr>

=item L<getcrown|Hub::Base::FileSystem/getcrown>

=item L<getext|Hub::Base::FileSystem/getext>

=item L<getgid|Hub::Perl::Language/getgid>

=item L<getname|Hub::Base::FileSystem/getname>

=item L<getns|Hub/getns>

=item L<getpath|Hub::Base::FileSystem/getpath>

=item L<getspec|Hub::Base::FileSystem/getspec>

=item L<getuid|Hub::Perl::Language/getuid>

=item L<getv|Hub::Data::Handlers/getv>

=item L<hashtoattrs|Hub::Misc::Transform/hashtoattrs>

=item L<hparse|Hub::Parse::Hash/hparse>

=item L<hprint|Hub::Parse::Hash/hprint>

=item L<indenttext|Hub::Console::Output/indenttext>

=item L<indexmatch|Hub::Perl::Language/indexmatch>

=item L<intdiv|Hub::Perl::Language/intdiv>

=item L<is_bipolar|Hub::Perl::Compare/is_bipolar>

=item L<jsstr|Hub::Misc::Transform/jsstr>

=item L<keydepth|Hub::Data::Address/keydepth>

=item L<keydepth_sort|Hub::Perl::Sort/keydepth_sort>

=item L<max|Hub::Perl::Language/max>

=item L<merge|Hub::Perl::Language/merge>

=item L<min|Hub::Perl::Language/min>

=item L<mkabsdir|Hub::Base::FileSystem/mkabsdir>

=item L<mkdiras|Hub::Base::FileSystem/mkdiras>

=item L<mkhandler|Hub::Data::Create/mkhandler>

=item L<mkinst|Hub/mkinst>

=item L<modexec|Hub::Base::Package/modexec>

=item L<mvfile|Hub::Base::FileSystem/mvfile>

=item L<nbspstr|Hub::Misc::Transform/nbspstr>

=item L<objopts|Hub::Perl::Language/objopts>

=item L<opts|Hub::Perl::Language/opts>

=item L<packcgi|Hub::Misc::Transform/packcgi>

=item L<parsefile|Hub::Base::FileSystem/parsefile>

=item L<populate|Hub::Misc::Transform/populate>

=item L<popwp|Hub::Base::FileSystem/popwp>

=item L<ps|Hub::Console::Output/ps>

=item L<pushwp|Hub::Base::FileSystem/pushwp>

=item L<readdir|Hub::Base::FileSystem/readdir>

=item L<readfile|Hub::Base::FileSystem/readfile>

=item L<realpath|Hub::Base::FileSystem/realpath>

=item L<regns|Hub/regns>

=item L<relpath|Hub::Base::FileSystem/relpath>

=item L<replace|Hub::Perl::Language/replace>

=item L<resolve|Hub::Data::Create/resolve>

=item L<rmdirrec|Hub::Base::FileSystem/rmdirrec>

=item L<rmfile|Hub::Base::FileSystem/rmfile>

=item L<rmval|Hub::Perl::Language/rmval>

=item L<safestr|Hub::Misc::Transform/safestr>

=item L<save_data|Hub::Data::Create/save_data>

=item L<setv|Hub::Data::Handlers/setv>

=item L<sizeof|Hub::Perl::Language/sizeof>

=item L<sort_compare|Hub::Perl::Compare/sort_compare>

=item L<sort_dir_list|Hub::Base::FileSystem/sort_dir_list>

=item L<srcpath|Hub::Base::FileSystem/srcpath>

=item L<store|Hub::Data::Handlers/store>

=item L<subset|Hub::Data::Create/subset>

=item L<subst|Hub::Perl::Language/subst>

=item L<touch|Hub::Perl::Language/touch>

=item L<trace|Hub/trace>

=item L<unpackcgi|Hub::Misc::Transform/unpackcgi>

=item L<varname|Hub::Data::Address/varname>

=item L<varparent|Hub::Data::Address/varparent>

=item L<varroot|Hub::Data::Address/varroot>

=item L<vartype|Hub::Data::Address/vartype>

=item L<writefile|Hub::Base::FileSystem/writefile>

=back


=head1 CLASSES

=over 4

=item L<DataExtractor|Hub::Parse::DataExtractor>

=item L<DataInjector|Hub::Parse::DataInjector>

=item L<Directory|Hub::Data::Directory>

=item L<File|Hub::Data::File>

=item L<FileParser|Hub::Parse::FileParser>

=item L<HashFile|Hub::Data::HashFile>

=item L<HtmlParser|Hub::Parse::HtmlParser>

=item L<Nest|Hub::Data::Nest>

=item L<NoOp|Hub::Base::NoOp>

=item L<Object|Hub::Base::Object>

=item L<Package|Hub::Base::Package>

=item L<Parser|Hub::Parse::Parser>

=item L<Registry|Hub::Base::Registry>

=item L<SortedHash|Hub::Data::SortedHash>

=item L<StandardParser|Hub::Parse::StandardParser>

=item L<Subset|Hub::Data::Subset>

=item L<Template|Hub::Parse::Template>

=item L<TextTemplate|Hub::Parse::TextTemplate>

=back


=head1 MODULES

=over 4

=item L<Hub|Hub>

=item L<Hub::Base::FileSystem|Hub::Base::FileSystem>

=item L<Hub::Base::Package|Hub::Base::Package>

=item L<Hub::Console::Output|Hub::Console::Output>

=item L<Hub::Data::Address|Hub::Data::Address>

=item L<Hub::Data::Create|Hub::Data::Create>

=item L<Hub::Data::FileCache|Hub::Data::FileCache>

=item L<Hub::Data::Handlers|Hub::Data::Handlers>

=item L<Hub::Misc::Time|Hub::Misc::Time>

=item L<Hub::Misc::Transform|Hub::Misc::Transform>

=item L<Hub::Parse::Hash|Hub::Parse::Hash>

=item L<Hub::Parse::Parser|Hub::Parse::Parser>

=item L<Hub::Perl::Compare|Hub::Perl::Compare>

=item L<Hub::Perl::Language|Hub::Perl::Language>

=item L<Hub::Perl::Sort|Hub::Perl::Sort>

=back



=head1 AUTHOR

Ryan Gies (ryangies@livesite.net)


=head1 COPYRIGHT

Copyright (C) 2006-2007 by Livesite Networks, LLC. All rights reserved.

Copyright (C) 2000-2005 by Ryan Gies. All rights reserved.


Redistribution and use in source and binary forms, with or without 
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, 
this list of conditions and the following disclaimer.

* The origin of this software must not be misrepresented; you must not 
claim that you wrote the original software. If you use this software in a 
product, an acknowledgment in the product documentation would be 
appreciated but is not required.

* Altered source versions must be plainly marked as such, and must not be 
misrepresented as being the original software.

* The name of the author may not be used to endorse or promote products 
derived from this software without specific prior written permission.


THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED 
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO 
EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT 
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING 
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
OF SUCH DAMAGE.

To the best of our knowledge, no patented algorithms have been used. However, we
do not have the resources to carry out a patent search, and therefore cannot 
give any guarantee of the above statement.


=head1 UPDATED

06/09/2007

=cut
