=head1 NAME

hubparse - Hub parser

=head1 SYNOPSIS

The Hub parser introduces the filesystem into the template context.  Along
with this, preprocessor and custom directives may be specified.  The basics
are that if you run in a directory which has a file C<./stuff/foo.txt>, you
may write the template:

  Here is your text:
  [#/stuff/foo.txt]


=head1 DESCRIPTION

into

  [#into "/another/file"]

  [#into "/another/file" as "variable"]

use

  [#use "/some/thing"]

  [#use "/some/thing" until "end_thing"]
  [#end "end_thing]

  [#use "/some/thing" as "foo"]
  [#/foo/bar]

foreach

  [#.num] is the item number

  [#foreach "item" in "/some/list"]
    [#item]
  [#end "foreach"]

  [#foreach "entry" in "/some/map"]
    [#entry:name] => [#entry:value]
  [#end "foreach"]

  [#foreach "entry" in "/some/map" sort="1"]
    [#entry:name] => [#entry:value]
  [#end "foreach"]

if

  [#if "/some/thing/exists"]
  [#end "if"]

  [#if "/some/thing" ?? "/some/thing/else"]
  [#end "if"]

  [#unless "/some/thing/exists"]
  [#end "unless"]

  [#unless "/some/thing" ?? "/some/thing/else"]
  [#end "unless"]

=head2 jsvar

  [#jsvar "/some/thing"]

When "/some/thing" is a hash, returns:

  {key1: 'value1', key2: 'value2' ...}

When "/some/thing" is an array, returns:

  ['item1', 'item2', ...]

When "/some/thing" is a scalar, returns:

  "escape it\'s content for\r\n for use in javascript"


=head1 AUTHOR

Ryan Gies (ryangies@livesite.net)


=head1 COPYRIGHT

Copyright (C) 2006-2007 by Livesite Networks, LLC. All rights reserved.

Copyright (C) 2000-2005 by Ryan Gies. All rights reserved.


Redistribution and use in source and binary forms, with or without 
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, 
this list of conditions and the following disclaimer.

* The origin of this software must not be misrepresented; you must not 
claim that you wrote the original software. If you use this software in a 
product, an acknowledgment in the product documentation would be 
appreciated but is not required.

* Altered source versions must be plainly marked as such, and must not be 
misrepresented as being the original software.

* The name of the author may not be used to endorse or promote products 
derived from this software without specific prior written permission.


THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED 
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO 
EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT 
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING 
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
OF SUCH DAMAGE.

To the best of our knowledge, no patented algorithms have been used. However, we
do not have the resources to carry out a patent search, and therefore cannot 
give any guarantee of the above statement.


=head1 UPDATED

08/02/2007

=cut
