#!/usr/bin/perl -w
# vim: syntax=perl
use strict;

# ------------------------------------------------------------------------------
# Library Test Harness
#
# CHANGES MADE HERE WILL BE OVERWRITTEN NEXT TIME `mktests.pl` IS RUN!
# ------------------------------------------------------------------------------
# This script was generated by `mktests.pl` on 08/29/2006 02:08:05pm
# ------------------------------------------------------------------------------

use Test::More tests => 105;

BEGIN {

  use_ok('Hub',':all')
  
};

our $result;

ok( &t0, "" );
ok( &t1, "" );
ok( &t2, "" );
ok( &t3, "" );
ok( &t4, "" );
ok( &t5, "" );
ok( &t6, "" );
ok( &t7, "" );
ok( &t8, "" );
ok( &t9, "" );
ok( &t10, "" );
ok( &t11, "" );
ok( &t12, "" );
ok( &t13, "" );
ok( &t14, "" );
ok( &t15, "" );
ok( &t16, "" );
ok( &t17, "" );
ok( &t18, "" );
ok( &t19, "" );
ok( &t20, "" );
ok( &t21, "" );
ok( &t22, "" );
ok( &t23, "" );
ok( &t24, "" );
ok( &t25, "" );
ok( &t26, "" );
ok( &t27, "" );
ok( &t28, "" );
ok( &t29, "" );
ok( &t30, "" );
ok( &t31, "" );
ok( &t32, "" );
ok( &t33, "" );
ok( &t34, "" );
ok( &t35, "" );
ok( &t36, "" );
ok( &t37, "" );
ok( &t38, "Simple (alphabetical) sort" );
ok( &t39, "" );
ok( &t40, "" );
ok( &t41, "" );
ok( &t42, "" );
ok( &t43, "" );
ok( &t44, "" );
ok( &t45, "" );
ok( &t46, "" );
ok( &t47, "" );
ok( &t48, "" );
ok( &t49, "" );
ok( &t50, "" );
ok( &t51, "" );
ok( &t52, "" );
ok( &t53, "" );
ok( &t54, "" );
ok( &t55, "" );
ok( &t56, "" );
ok( &t57, "" );
ok( &t58, "" );
ok( &t59, "" );
ok( &t60, "" );
ok( &t61, "" );
ok( &t62, "" );
ok( &t63, "" );
ok( &t64, "" );
ok( &t65, "" );
ok( &t66, "" );
ok( !&t67, "" );
ok( &t68, "none are defined" );
ok( &t69, "only one is defined" );
ok( &t70, "both are defined" );
ok( &t71, "one is defined" );
ok( &t72, "" );
ok( &t73, "" );
ok( &t74, "" );
ok( &t75, "" );
ok( &t76, "" );
ok( &t77, "" );
ok( &t78, "" );
ok( &t79, "at-underscore contains everyting but the '-with' option" );
ok( &t80, "Test return value" );
ok( &t81, "" );
ok( &t82, "" );
ok( &t83, "" );
ok( &t84, "" );
ok( &t85, "" );
ok( &t86, "" );
ok( &t87, "" );
ok( &t88, "" );
ok( &t89, "" );
ok( &t90, "" );
ok( &t91, "" );
ok( &t92, "" );
ok( &t93, "Two integers" );
ok( &t94, "Three integers" );
ok( &t95, "Three integers" );
ok( &t96, "One integer" );
ok( &t97, "Undefined value" );
ok( &t98, "Zero" );
ok( &t99, "Three decimal values" );
ok( &t100, "Three decimal values" );
ok( &t101, "3 divided by 2 is 1R1" );
ok( &t102, "" );
ok( &t103, "" );



# ------------------------------------------------------------------------------
# t0
# 
# Generated from /home/hub/lib/Hub/Perl/Compare.pm line: 57
# ------------------------------------------------------------------------------

sub t0 {

    $result = eval { compare('eq','',undef);
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t0

# ------------------------------------------------------------------------------
# t1
# 
# Generated from /home/hub/lib/Hub/Perl/Compare.pm line: 58
# ------------------------------------------------------------------------------

sub t1 {

    $result = eval { compare('eq','abc','abc');
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t1

# ------------------------------------------------------------------------------
# t2
# 
# Generated from /home/hub/lib/Hub/Perl/Compare.pm line: 59
# ------------------------------------------------------------------------------

sub t2 {

    $result = eval { compare('ne','abc','Abc');
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t2

# ------------------------------------------------------------------------------
# t3
# 
# Generated from /home/hub/lib/Hub/Perl/Compare.pm line: 60
# ------------------------------------------------------------------------------

sub t3 {

    $result = eval { compare('eq','abc',undef);
 };

    $@ and die $@;

    return $result ? 0 : 1;

}#t3

# ------------------------------------------------------------------------------
# t4
# 
# Generated from /home/hub/lib/Hub/Perl/Compare.pm line: 61
# ------------------------------------------------------------------------------

sub t4 {

    $result = eval { compare('!~','abc','A');
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t4

# ------------------------------------------------------------------------------
# t5
# 
# Generated from /home/hub/lib/Hub/Perl/Compare.pm line: 62
# ------------------------------------------------------------------------------

sub t5 {

    $result = eval { compare('=~','abc','a');
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t5

# ------------------------------------------------------------------------------
# t6
# 
# Generated from /home/hub/lib/Hub/Perl/Compare.pm line: 63
# ------------------------------------------------------------------------------

sub t6 {

    $result = eval { compare('==',1234,1234);
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t6

# ------------------------------------------------------------------------------
# t7
# 
# Generated from /home/hub/lib/Hub/Perl/Compare.pm line: 64
# ------------------------------------------------------------------------------

sub t7 {

    $result = eval { compare('>=',1234,1234);
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t7

# ------------------------------------------------------------------------------
# t8
# 
# Generated from /home/hub/lib/Hub/Perl/Compare.pm line: 65
# ------------------------------------------------------------------------------

sub t8 {

    $result = eval { compare('eqic','abc','Abc');
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t8

# ------------------------------------------------------------------------------
# t9
# 
# Generated from /home/hub/lib/Hub/Perl/Compare.pm line: 66
# ------------------------------------------------------------------------------

sub t9 {

    $result = eval { compare('==',undef,undef);
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t9

# ------------------------------------------------------------------------------
# t10
# 
# Generated from /home/hub/lib/Hub/Perl/Compare.pm line: 67
# ------------------------------------------------------------------------------

sub t10 {

    $result = eval { compare('==',0,undef);
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t10

# ------------------------------------------------------------------------------
# t11
# 
# Generated from /home/hub/lib/Hub/Perl/Compare.pm line: 68
# ------------------------------------------------------------------------------

sub t11 {

    $result = eval { my @numbers = ( 20, 1, 10, 2 );
              join ';', sort { &compare('<=>',$a,$b) } @numbers;
 };

    $@ and die $@;

    return $result eq "1;2;10;20";

}#t11

# ------------------------------------------------------------------------------
# t12
# 
# Generated from /home/hub/lib/Hub/Knots/Defined.pm line: 9
# ------------------------------------------------------------------------------

sub t12 {

    $result = eval { 
    my $h = {};

    playnice( $h );

    $$h{'foo'} = 'bar';

    $$h{'foo'};

 };

    $@ and die $@;

    return $result eq "bar";

}#t12

# ------------------------------------------------------------------------------
# t13
# 
# Generated from /home/hub/lib/Hub/Knots/Addressable.pm line: 156
# ------------------------------------------------------------------------------

sub t13 {

    $result = eval { 
    use Hub;
    my %h = ();

    tie %h, 'Hub::Knots::Addressable';

    $h{'/food/fruit'} = [
        {
            'name'  => 'apple',
            'id'    => 123,
            'grown' => 'Washington',
            'color' => 'red',
        },
    ];

    $h{'/food/fruit/apple/grown'};

 };

    $@ and die $@;

    return $result eq "Washington";

}#t13

# ------------------------------------------------------------------------------
# t14
# 
# Generated from /home/hub/lib/Hub.pm line: 291
# ------------------------------------------------------------------------------

sub t14 {

    $result = eval { ref( mkinst( 'Logger' ) ) eq 'Hub::Base::Logger';
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t14

# ------------------------------------------------------------------------------
# t15
# 
# Generated from /home/hub/lib/Hub.pm line: 292
# ------------------------------------------------------------------------------

sub t15 {

    $result = eval { mkinst( 'DoesNotExist' );
 };

    $@ and do { $result = $@; chomp $result };

    return $@ ? 1 : 0;

}#t15

# ------------------------------------------------------------------------------
# t16
# 
# Generated from /home/hub/lib/Hub.pm line: 395
# ------------------------------------------------------------------------------

sub t16 {

    $result = eval { Hub::blahblahblah();

 };

    $@ and do { $result = $@; chomp $result };

    return $@ ? 1 : 0;

}#t16

# ------------------------------------------------------------------------------
# t17
# 
# Generated from /home/hub/lib/Hub/Parse/Parser.pm line: 85
# ------------------------------------------------------------------------------

sub t17 {

    $result = eval { my $parser = mkinst( 'Parser', -template => 'Hello <#who>' );
              ${$parser->populate( { who => 'World' } )};
 };

    $@ and die $@;

    return $result eq "Hello World";

}#t17

# ------------------------------------------------------------------------------
# t18
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 28
# ------------------------------------------------------------------------------

sub t18 {

    $result = eval { keydepth( 'and:then:came:the:rain' )
 };

    $@ and die $@;

    return $result eq "4";

}#t18

# ------------------------------------------------------------------------------
# t19
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 44
# ------------------------------------------------------------------------------

sub t19 {

    $result = eval { vartype( );
 };

    $@ and die $@;

    return $result eq "";

}#t19

# ------------------------------------------------------------------------------
# t20
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 45
# ------------------------------------------------------------------------------

sub t20 {

    $result = eval { vartype( "clr-bg" );
 };

    $@ and die $@;

    return $result eq "clr";

}#t20

# ------------------------------------------------------------------------------
# t21
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 46
# ------------------------------------------------------------------------------

sub t21 {

    $result = eval { vartype( "clr-bg", "default" );
 };

    $@ and die $@;

    return $result eq "clr";

}#t21

# ------------------------------------------------------------------------------
# t22
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 47
# ------------------------------------------------------------------------------

sub t22 {

    $result = eval { vartype( "whatev", "default" );
 };

    $@ and die $@;

    return $result eq "default";

}#t22

# ------------------------------------------------------------------------------
# t23
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 48
# ------------------------------------------------------------------------------

sub t23 {

    $result = eval { vartype( "whatev" );
 };

    $@ and die $@;

    return $result eq "";

}#t23

# ------------------------------------------------------------------------------
# t24
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 49
# ------------------------------------------------------------------------------

sub t24 {

    $result = eval { vartype( "a:b:c" );
 };

    $@ and die $@;

    return $result eq "";

}#t24

# ------------------------------------------------------------------------------
# t25
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 50
# ------------------------------------------------------------------------------

sub t25 {

    $result = eval { vartype( "x-a:b:c" );
 };

    $@ and die $@;

    return $result eq "x";

}#t25

# ------------------------------------------------------------------------------
# t26
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 51
# ------------------------------------------------------------------------------

sub t26 {

    $result = eval { vartype( "a:b:x-c" );
 };

    $@ and die $@;

    return $result eq "x";

}#t26

# ------------------------------------------------------------------------------
# t27
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 74
# ------------------------------------------------------------------------------

sub t27 {

    $result = eval { varroot( "p001:items:1002:text-description" );
 };

    $@ and die $@;

    return $result eq "p001";

}#t27

# ------------------------------------------------------------------------------
# t28
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 75
# ------------------------------------------------------------------------------

sub t28 {

    $result = eval { varroot( "p001" );
 };

    $@ and die $@;

    return $result eq "p001";

}#t28

# ------------------------------------------------------------------------------
# t29
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 92
# ------------------------------------------------------------------------------

sub t29 {

    $result = eval { varname( "p001:items:1002:text-desc" );
 };

    $@ and die $@;

    return $result eq "text-desc";

}#t29

# ------------------------------------------------------------------------------
# t30
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 93
# ------------------------------------------------------------------------------

sub t30 {

    $result = eval { varname( "p001" );
 };

    $@ and die $@;

    return $result eq "p001";

}#t30

# ------------------------------------------------------------------------------
# t31
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 111
# ------------------------------------------------------------------------------

sub t31 {

    $result = eval { varparent( "p001:items:12:1000" );
 };

    $@ and die $@;

    return $result eq "p001:items:12";

}#t31

# ------------------------------------------------------------------------------
# t32
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 112
# ------------------------------------------------------------------------------

sub t32 {

    $result = eval { varparent( "p001:items:10:subs:100" );
 };

    $@ and die $@;

    return $result eq "p001:items:10:subs";

}#t32

# ------------------------------------------------------------------------------
# t33
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 113
# ------------------------------------------------------------------------------

sub t33 {

    $result = eval { varparent( "p001" );
 };

    $@ and die $@;

    return $result eq "";

}#t33

# ------------------------------------------------------------------------------
# t34
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 132
# ------------------------------------------------------------------------------

sub t34 {

    $result = eval { dotaddr( "p004:proj:1000" );
 };

    $@ and die $@;

    return $result eq "p004.proj.1000";

}#t34

# ------------------------------------------------------------------------------
# t35
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 133
# ------------------------------------------------------------------------------

sub t35 {

    $result = eval { dotaddr( "p004:proj:1000:name" );
 };

    $@ and die $@;

    return $result eq "p004.proj.1000.name";

}#t35

# ------------------------------------------------------------------------------
# t36
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 134
# ------------------------------------------------------------------------------

sub t36 {

    $result = eval { dotaddr( "p001" );
 };

    $@ and die $@;

    return $result eq "p001";

}#t36

# ------------------------------------------------------------------------------
# t37
# 
# Generated from /home/hub/lib/Hub/Data/Address.pm line: 135
# ------------------------------------------------------------------------------

sub t37 {

    $result = eval { dotaddr( "" );
 };

    $@ and die $@;

    return $result eq "";

}#t37

# ------------------------------------------------------------------------------
# t38
# 
# Generated from /home/hub/lib/Hub/Perl/Sort.pm line: 27
# ------------------------------------------------------------------------------

sub t38 {

    $result = eval {     my @months = qw/Jan Feb Mar/;
    my @sorted = anonsort( \@months );
    return join ',', @sorted;
 };

    $@ and die $@;

    return $result eq "Feb,Jan,Mar";

}#t38

# ------------------------------------------------------------------------------
# t39
# 
# Generated from /home/hub/lib/Hub/Data/File.pm line: 1174
# ------------------------------------------------------------------------------

sub t39 {

    $result = eval { safefn( 'alsk/lsdkfj' );
 };

    $@ and die $@;

    return $result eq "alsk_2f_lsdkfj";

}#t39

# ------------------------------------------------------------------------------
# t40
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 46
# ------------------------------------------------------------------------------

sub t40 {

    $result = eval { safestr( 'Dogs (Waters, Gilmour) 17:06' );
 };

    $@ and die $@;

    return $result eq "Dogs_20__28_Waters_2c__20_Gilmour_29__20_17_3a_06";

}#t40

# ------------------------------------------------------------------------------
# t41
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 237
# ------------------------------------------------------------------------------

sub t41 {

    $result = eval { fixpath( "../../../users/newuser/web/bin/../src/screens" );
 };

    $@ and die $@;

    return $result eq "../../../users/newuser/web/src/screens";

}#t41

# ------------------------------------------------------------------------------
# t42
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 240
# ------------------------------------------------------------------------------

sub t42 {

    $result = eval { fixpath( "users/newuser/web/" );
 };

    $@ and die $@;

    return $result eq "users/newuser/web";

}#t42

# ------------------------------------------------------------------------------
# t43
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 243
# ------------------------------------------------------------------------------

sub t43 {

    $result = eval { fixpath( "users/../web/bin/../src" );
 };

    $@ and die $@;

    return $result eq "web/src";

}#t43

# ------------------------------------------------------------------------------
# t44
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 246
# ------------------------------------------------------------------------------

sub t44 {

    $result = eval { fixpath( "users//newuser" );
 };

    $@ and die $@;

    return $result eq "users/newuser";

}#t44

# ------------------------------------------------------------------------------
# t45
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 249
# ------------------------------------------------------------------------------

sub t45 {

    $result = eval { fixpath( "users//newuser/./files" );
 };

    $@ and die $@;

    return $result eq "users/newuser/files";

}#t45

# ------------------------------------------------------------------------------
# t46
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 252
# ------------------------------------------------------------------------------

sub t46 {

    $result = eval { fixpath( "http://site/users//newuser" );
 };

    $@ and die $@;

    return $result eq "http://site/users/newuser";

}#t46

# ------------------------------------------------------------------------------
# t47
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 254
# ------------------------------------------------------------------------------

sub t47 {

    $result = eval { fixpath( '/home/hub/build/../../../out/doc/pod' );
 };

    $@ and die $@;

    return $result eq "/out/doc/pod";

}#t47

# ------------------------------------------------------------------------------
# t48
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 324
# ------------------------------------------------------------------------------

sub t48 {

    $result = eval { relpath( "/home/docs", "/home/docs/install", -asdir );
 };

    $@ and die $@;

    return $result eq "..";

}#t48

# ------------------------------------------------------------------------------
# t49
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 325
# ------------------------------------------------------------------------------

sub t49 {

    $result = eval { relpath( "/home/docs", "/home/docs/README.txt" );
 };

    $@ and die $@;

    return $result eq ".";

}#t49

# ------------------------------------------------------------------------------
# t50
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 326
# ------------------------------------------------------------------------------

sub t50 {

    $result = eval { relpath( "/home/src", "/home/docs/install", -asdir );
 };

    $@ and die $@;

    return $result eq "../../src";

}#t50

# ------------------------------------------------------------------------------
# t51
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 328
# ------------------------------------------------------------------------------

sub t51 {

    $result = eval { relpath( "/home/docs/README.txt", "/home/docs", -asdir );
 };

    $@ and die $@;

    return $result eq "README.txt";

}#t51

# ------------------------------------------------------------------------------
# t52
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 582
# ------------------------------------------------------------------------------

sub t52 {

    $result = eval { datetime( );
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t52

# ------------------------------------------------------------------------------
# t53
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 583
# ------------------------------------------------------------------------------

sub t53 {

    $result = eval { datetime( 1045837284 );
 };

    $@ and die $@;

    return $result eq "02/21/2003 06:21:24";

}#t53

# ------------------------------------------------------------------------------
# t54
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 584
# ------------------------------------------------------------------------------

sub t54 {

    $result = eval { datetime( 1045837284, -nosec );
 };

    $@ and die $@;

    return $result eq "02/21/2003 06:21";

}#t54

# ------------------------------------------------------------------------------
# t55
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 585
# ------------------------------------------------------------------------------

sub t55 {

    $result = eval { datetime( 1045837284, -noyear );
 };

    $@ and die $@;

    return $result eq "02/21 06:21:24";

}#t55

# ------------------------------------------------------------------------------
# t56
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 586
# ------------------------------------------------------------------------------

sub t56 {

    $result = eval { datetime( 1045837284, -ampm );
 };

    $@ and die $@;

    return $result eq "02/21/2003 06:21:24am";

}#t56

# ------------------------------------------------------------------------------
# t57
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 587
# ------------------------------------------------------------------------------

sub t57 {

    $result = eval { datetime( 1045837284, -nozeros );
 };

    $@ and die $@;

    return $result eq "2/21/2003 6:21:24";

}#t57

# ------------------------------------------------------------------------------
# t58
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 588
# ------------------------------------------------------------------------------

sub t58 {

    $result = eval { datetime( 1045837284, -notime );
 };

    $@ and die $@;

    return $result eq "02/21/2003";

}#t58

# ------------------------------------------------------------------------------
# t59
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 589
# ------------------------------------------------------------------------------

sub t59 {

    $result = eval { datetime( 1045837284, -nodate );
 };

    $@ and die $@;

    return $result eq "06:21:24";

}#t59

# ------------------------------------------------------------------------------
# t60
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 590
# ------------------------------------------------------------------------------

sub t60 {

    $result = eval { datetime( 1045837284, -letter );
 };

    $@ and die $@;

    return $result eq "February 21, 2003 06:21:24";

}#t60

# ------------------------------------------------------------------------------
# t61
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 594
# ------------------------------------------------------------------------------

sub t61 {

    $result = eval { datetime( 1045837284, -ampm, -nosec );              
 };

    $@ and die $@;

    return $result eq "02/21/2003 06:21am";

}#t61

# ------------------------------------------------------------------------------
# t62
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 597
# ------------------------------------------------------------------------------

sub t62 {

    $result = eval { datetime( 1045837284, -nosec, -nozeros, -noyear );
 };

    $@ and die $@;

    return $result eq "2/21 6:21";

}#t62

# ------------------------------------------------------------------------------
# t63
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 602
# ------------------------------------------------------------------------------

sub t63 {

    $result = eval { datetime( 1045837284, "nosec,noyear" );
 };

    $@ and die $@;

    return $result eq "02/21 06:21";

}#t63

# ------------------------------------------------------------------------------
# t64
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 792
# ------------------------------------------------------------------------------

sub t64 {

    $result = eval { ps( 10, "this is really short but splits on ten chars" );


 };

    $@ and die $@;

    return $result eq "this is re
ally short
 but split
s on ten c
hars";

}#t64

# ------------------------------------------------------------------------------
# t65
# 
# Generated from /home/hub/lib/Hub/Parse/Transform.pm line: 800
# ------------------------------------------------------------------------------

sub t65 {

    $result = eval { ps( 10, "this is really short but splits on ten chars", 3 );

 };

    $@ and die $@;

    return $result eq "this is re
   ally short
    but split
   s on ten c
   hars";

}#t65

# ------------------------------------------------------------------------------
# t66
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 61
# ------------------------------------------------------------------------------

sub t66 {

    $result = eval { join 'X', asa(undef);
 };

    $@ and die $@;

    return $result eq "";

}#t66

# ------------------------------------------------------------------------------
# t67
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 113
# ------------------------------------------------------------------------------

sub t67 {

    $result = eval { my $compression = check( '-test=eval', 'use IO::Zlib' ) ? 1 : 0;
 };

    $@ and do { $result = $@; chomp $result };

    return $@ ? 1 : 0;

}#t67

# ------------------------------------------------------------------------------
# t68
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 123
# ------------------------------------------------------------------------------

sub t68 {

    $result = eval { check( undef, undef, undef );
 };

    $@ and die $@;

    return $result ? 0 : 1;

}#t68

# ------------------------------------------------------------------------------
# t69
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 124
# ------------------------------------------------------------------------------

sub t69 {

    $result = eval { check( 1, undef );
 };

    $@ and die $@;

    return $result ? 0 : 1;

}#t69

# ------------------------------------------------------------------------------
# t70
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 125
# ------------------------------------------------------------------------------

sub t70 {

    $result = eval { check( 1, 1 );
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t70

# ------------------------------------------------------------------------------
# t71
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 126
# ------------------------------------------------------------------------------

sub t71 {

    $result = eval { check( 1, undef, -opr => 'or' );

 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t71

# ------------------------------------------------------------------------------
# t72
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 128
# ------------------------------------------------------------------------------

sub t72 {

    $result = eval { check( -opr => 'xor', 1, 1 );
 };

    $@ and die $@;

    return $result ? 0 : 1;

}#t72

# ------------------------------------------------------------------------------
# t73
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 129
# ------------------------------------------------------------------------------

sub t73 {

    $result = eval { check( -opr => 'xor', undef, undef );

 };

    $@ and die $@;

    return $result ? 0 : 1;

}#t73

# ------------------------------------------------------------------------------
# t74
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 131
# ------------------------------------------------------------------------------

sub t74 {

    $result = eval { check( -opr => 'xor', undef, 1 );
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t74

# ------------------------------------------------------------------------------
# t75
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 132
# ------------------------------------------------------------------------------

sub t75 {

    $result = eval { check( -opr => 'xor', 1, undef );

 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t75

# ------------------------------------------------------------------------------
# t76
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 134
# ------------------------------------------------------------------------------

sub t76 {

    $result = eval { check( -opr => 'xor', 1, undef, 1, undef );
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t76

# ------------------------------------------------------------------------------
# t77
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 135
# ------------------------------------------------------------------------------

sub t77 {

    $result = eval { check( -opr => 'xor', 1, undef, 1, 1, undef );
 };

    $@ and die $@;

    return $result ? 0 : 1;

}#t77

# ------------------------------------------------------------------------------
# t78
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 136
# ------------------------------------------------------------------------------

sub t78 {

    $result = eval { check( -opr => 'xor', undef, 1, undef, 1 );
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t78

# ------------------------------------------------------------------------------
# t79
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 284
# ------------------------------------------------------------------------------

sub t79 {

    $result = eval { 
   sub myjoin {
      my $opts = Hub::opts( \@_ );
      return join( $$opts{'with'}, @_ );
   }

   myjoin( 'a', 'b', '-with=;', 'c', 'd' );
 };

    $@ and die $@;

    return $result eq "a;b;c;d";

}#t79

# ------------------------------------------------------------------------------
# t80
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 430
# ------------------------------------------------------------------------------

sub t80 {

    $result = eval { 
  my $obj = mkinst( 'Object' );
  my @result = objopts( [ $obj ] );
  join( ',', map { ref($_) } @result );

 };

    $@ and die $@;

    return $result eq "Hub::Base::Object,";

}#t80

# ------------------------------------------------------------------------------
# t81
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 661
# ------------------------------------------------------------------------------

sub t81 {

    $result = eval { Hub::expect( -match => 'and|or|xor', 'and' );
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t81

# ------------------------------------------------------------------------------
# t82
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 662
# ------------------------------------------------------------------------------

sub t82 {

    $result = eval { Hub::expect( HASH => {}, HASH => {} );
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t82

# ------------------------------------------------------------------------------
# t83
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 663
# ------------------------------------------------------------------------------

sub t83 {

    $result = eval { Hub::expect( -blessed => {} );
 };

    $@ and do { $result = $@; chomp $result };

    return $@ ? 1 : 0;

}#t83

# ------------------------------------------------------------------------------
# t84
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 664
# ------------------------------------------------------------------------------

sub t84 {

    $result = eval { Hub::expect( -blessed => mkinst( 'Object' ) );
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t84

# ------------------------------------------------------------------------------
# t85
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 665
# ------------------------------------------------------------------------------

sub t85 {

    $result = eval { Hub::expect( -match => 'and|or|xor', 'if', 'or', 'and' );
 };

    $@ and do { $result = $@; chomp $result };

    return $@ ? 1 : 0;

}#t85

# ------------------------------------------------------------------------------
# t86
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 666
# ------------------------------------------------------------------------------

sub t86 {

    $result = eval { Hub::expect( ARRAY => {} );
 };

    $@ and do { $result = $@; chomp $result };

    return $@ ? 1 : 0;

}#t86

# ------------------------------------------------------------------------------
# t87
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 667
# ------------------------------------------------------------------------------

sub t87 {

    $result = eval { Hub::expect( -blessed => 'abc' );
 };

    $@ and do { $result = $@; chomp $result };

    return $@ ? 1 : 0;

}#t87

# ------------------------------------------------------------------------------
# t88
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 668
# ------------------------------------------------------------------------------

sub t88 {

    $result = eval { Hub::expect( -ref => 'HASH', {} );
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t88

# ------------------------------------------------------------------------------
# t89
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 669
# ------------------------------------------------------------------------------

sub t89 {

    $result = eval { Hub::expect( -ref => 'HASH', mkinst('Object') );
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t89

# ------------------------------------------------------------------------------
# t90
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 724
# ------------------------------------------------------------------------------

sub t90 {

    $result = eval { Hub::fear( HASH => {} );
 };

    $@ and do { $result = $@; chomp $result };

    return $@ ? 1 : 0;

}#t90

# ------------------------------------------------------------------------------
# t91
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 725
# ------------------------------------------------------------------------------

sub t91 {

    $result = eval { Hub::fear( HASH => [] );
 };

    $@ and die $@;

    return $result ? 1 : 0;

}#t91

# ------------------------------------------------------------------------------
# t92
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 741
# ------------------------------------------------------------------------------

sub t92 {

    $result = eval { abort( -msg => 'Goddamn hippies' );
 };

    $@ and do { $result = $@; chomp $result };

    return $@ ? 1 : 0;

}#t92

# ------------------------------------------------------------------------------
# t93
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 854
# ------------------------------------------------------------------------------

sub t93 {

    $result = eval { Hub::min(1,2);
 };

    $@ and die $@;

    return $result eq "1";

}#t93

# ------------------------------------------------------------------------------
# t94
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 855
# ------------------------------------------------------------------------------

sub t94 {

    $result = eval { Hub::min(2,1,3);
 };

    $@ and die $@;

    return $result eq "1";

}#t94

# ------------------------------------------------------------------------------
# t95
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 856
# ------------------------------------------------------------------------------

sub t95 {

    $result = eval { Hub::min(2,-1,3);
 };

    $@ and die $@;

    return $result eq "-1";

}#t95

# ------------------------------------------------------------------------------
# t96
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 857
# ------------------------------------------------------------------------------

sub t96 {

    $result = eval { Hub::min(1);
 };

    $@ and die $@;

    return $result eq "1";

}#t96

# ------------------------------------------------------------------------------
# t97
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 858
# ------------------------------------------------------------------------------

sub t97 {

    $result = eval { Hub::min(1,undef);
 };

    $@ and die $@;

    return $result eq "1";

}#t97

# ------------------------------------------------------------------------------
# t98
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 859
# ------------------------------------------------------------------------------

sub t98 {

    $result = eval { Hub::min(undef,1,0);
 };

    $@ and die $@;

    return $result eq "0";

}#t98

# ------------------------------------------------------------------------------
# t99
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 860
# ------------------------------------------------------------------------------

sub t99 {

    $result = eval { Hub::min(.009,1.001);
 };

    $@ and die $@;

    return $result eq "0.009";

}#t99

# ------------------------------------------------------------------------------
# t100
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 876
# ------------------------------------------------------------------------------

sub t100 {

    $result = eval { Hub::max(.009,-1.01,2,undef,0);
 };

    $@ and die $@;

    return $result eq "2";

}#t100

# ------------------------------------------------------------------------------
# t101
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 893
# ------------------------------------------------------------------------------

sub t101 {

    $result = eval { join(',',Hub::intdiv(3,2));
 };

    $@ and die $@;

    return $result eq "1,1";

}#t101

# ------------------------------------------------------------------------------
# t102
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 1337
# ------------------------------------------------------------------------------

sub t102 {

    $result = eval { 
  my $x = 'like catfood';
  Hub::checksum( 'my', { cats => 'breath' }, ( 'smells', $x ) );

 };

    $@ and die $@;

    return $result eq "2023611966";

}#t102

# ------------------------------------------------------------------------------
# t103
# 
# Generated from /home/hub/lib/Hub/Perl/Language.pm line: 2183
# ------------------------------------------------------------------------------

sub t103 {

    $result = eval { join( ';', dice( "a{b{c}}c{d}" ) );
 };

    $@ and die $@;

    return $result eq "a;{b{c}};c;{d}";

}#t103

