=head1 NAME

Hub::Webapp::CGI - 

Part of the L<Hub Library|hublib>

=head1 SYNOPSIS



=head1 DESCRIPTION



=head1 METHODS

=begin html

<table><tr><td>
<a class="methlink" href="#item_process_fcgi_request">process_fcgi_request</a>

</td><td>
<a class="methlink" href="#item_process_request">process_request</a>

</td></tr></table>

=end html


=over 4

=item process_fcgi_request

B<>



=back

=over 4

=item process_request

B<>



=back

=head1 INTERNAL

=begin html

<table><tr><td>
<a class="methlink" href="#item__wrapcallback">_wrapcallback</a>

</td></tr></table>

=end html


=over 4

=item _wrapcallback

B<>



=back

=head1 AUTHOR



Ryan Gies

=head1 COPYRIGHT



Copyright (c) 2006 Livesite Networks, LLC.  All rights reserved.

Copyright (c) 2000-2005 Ryan Gies.  All rights reserved.

=head1 UPDATED

This file created by  on  at 

=cut
