=head1 NAME

Hub::Webapp::HTTP - HTTP Connection Wrapper

Part of the L<Hub Library|hublib>

=head1 SYNOPSIS


    use Hub qw(:standard);
    callback( &main );
    sub main {
        my $resp = httpget('http://my.server.ip');
        print $$resp{'body'};
    }


=head1 DESCRIPTION



=head1 METHODS

=begin html

<table><tr><td>
<a class="methlink" href="#item_http">http</a>

</td><td>
<a class="methlink" href="#item_httpget">httpget</a>

</td></tr></table>

=end html


=over 4

=item http

B<HTTP Transmit and respond>


 Usage: http $uri, $content, [option]


options:


  -cookie_jar=$cookie_jar         Implements HTTP::Cookies
  -raw                            Return the raw HTTP::Response object

  -method=GET|POST                HTTP Method
  -agent=$string                  User agent identifier
  -content_type=$string           Content type



=back

=over 4

=item httpget

B<HTTP Get>



=back

=head1 INTERNAL

=begin html

<table><tr><td>
<a class="methlink" href="#item__uri_split">_uri_split</a>

</td></tr></table>

=end html


=over 4

=item _uri_split

B<Obtain pieces of URI information>



=back

=head1 AUTHOR



Ryan Gies

=head1 COPYRIGHT



Copyright (c) 2006 Livesite Networks, LLC.  All rights reserved.

Copyright (c) 2000-2005 Ryan Gies.  All rights reserved.

=head1 UPDATED

This file created by  on  at 

=cut
